### ISSUE TITLE
Error Formatting FIle - No parser could be inferred to for file: x.php

### ISSUE THREAD

**Issue by clickamplify** [Hirse/brackets-prettier#3]
Just installed on latest versions of Mint and Brackets, tried using Prettier, got this message and it did not format my .php file.

![image](https://user-images.githubusercontent.com/34973145/76970900-cd2d5880-692c-11ea-8599-541cf1cd15d3.png)

If there is a any way I can help you with debugging, I will help gladly.

**Comment by alekexe** [comment]
Still no fix 5 days later

**Comment by Hirse** [comment]
PHP is not supported by prettier by default.
I have created a branch that adds the PHP plugin: https://github.com/Hirse/brackets-prettier/tree/php

Please try it out to see if this would work for you:
[hirse.brackets-prettier-1.1.0-php.zip](https://github.com/Hirse/brackets-prettier/files/4963250/hirse.brackets-prettier-1.1.0-php.zip)
